WITH PDOMNAME AS (
    SELECT ? AS DOM_NAME FROM DUAL
)
SELECT PNAMES             AS NAMES
     , PDBMS_TABLE        AS DBMS_TABLE
     , PFROM_CLASS        AS FROM_CLASS
     , PTO_CLASS          AS TO_CLASS
     , PFROM_RELATIONSHIP AS FROM_RELATIONSHIP
     , PTO_RELATIONSHIP   AS TO_RELATIONSHIP
     , PREMARKS           AS REMARKS
     , POWNERS            AS OWNERS
  FROM PSYSRELOBJECTCLASSINFO
 WHERE (PNAMES = (SELECT DOM_NAME FROM PDOMNAME) OR
        PFROM_CLASS = (SELECT DOM_NAME FROM PDOMNAME) OR
        PFROM_CLASS LIKE '%,' || (SELECT DOM_NAME FROM PDOMNAME) OR
        PFROM_CLASS LIKE (SELECT DOM_NAME FROM PDOMNAME) || ',%' OR
        PFROM_CLASS LIKE '%,' || (SELECT DOM_NAME FROM PDOMNAME) ||',%' OR
        PTO_CLASS = (SELECT DOM_NAME FROM PDOMNAME) OR
        PTO_CLASS LIKE '%,' || (SELECT DOM_NAME FROM PDOMNAME) OR
        PTO_CLASS LIKE (SELECT DOM_NAME FROM PDOMNAME) || ',%' OR
        PTO_CLASS LIKE '%,' || (SELECT DOM_NAME FROM PDOMNAME) || ',%' OR
        PFROM_RELATIONSHIP = (SELECT DOM_NAME FROM PDOMNAME) OR
        PFROM_RELATIONSHIP LIKE '%,' || (SELECT DOM_NAME FROM PDOMNAME) OR
        PFROM_RELATIONSHIP LIKE (SELECT DOM_NAME FROM PDOMNAME) || ',%' OR
        PFROM_RELATIONSHIP LIKE '%,' || (SELECT DOM_NAME FROM PDOMNAME) || ',%' OR
        PTO_RELATIONSHIP = (SELECT DOM_NAME FROM PDOMNAME) OR
        PTO_RELATIONSHIP LIKE '%,' || (SELECT DOM_NAME FROM PDOMNAME) OR
        PTO_RELATIONSHIP LIKE (SELECT DOM_NAME FROM PDOMNAME) || ',%' OR
        PTO_RELATIONSHIP LIKE '%,' || (SELECT DOM_NAME FROM PDOMNAME) || ',%'
       )